export const questions = [
    { question: "지구의 대기에는 산소가 약 21% 포함되어 있다.", answer: "O" },
    { question: "탄소는 지구상에서 가장 흔한 원소이다.", answer: "X" },
    { question: "빛은 파동과 입자의 성질을 모두 가진다.", answer: "O" },
    { question: "염산(HCl)은 산성이며, 수용액에서 수소 이온(H⁺)을 방출한다.", answer: "O" },
    { question: "달은 자체적으로 빛을 내는 천체이다.", answer: "X" },
    { question: "전류가 흐르면 자석 주변에서 전기장이 형성된다.", answer: "X" },
    { question: "모든 금속은 자석에 붙는다.", answer: "X" },
    { question: "지구의 중심부는 고체 상태이다.", answer: "O" },
    { question: "모든 생명체는 세포로 이루어져 있다.", answer: "O" },
    { question: "대류는 고온에서 저온으로 열이 전달되는 과정이다.", answer: "O" },
    { question: "원소의 주기율표에서 오른쪽으로 갈수록 금속의 성질이 강해진다.", answer: "X" },
    { question: "지구는 태양계를 포함한 은하수의 일부이다.", answer: "O" },
    { question: "광합성은 물과 이산화탄소를 산소와 포도당으로 변환하는 과정이다.", answer: "O" },
    { question: "우주에는 행성보다 별이 더 많다.", answer: "O" },
    { question: "수성은 태양계에서 가장 작은 행성이다.", answer: "O" },
    { question: "질소는 공기 중에 약 78% 포함되어 있다.", answer: "O" },
    { question: "포화 지방은 상온에서 고체 상태로 존재한다.", answer: "O" },
    { question: "원자의 중심에는 양성자와 중성자로 이루어진 핵이 있다.", answer: "O" },
    { question: "우라늄은 원자 번호가 가장 작은 원소이다.", answer: "X" },
    { question: "태양 에너지는 핵분열에 의해 생성된다.", answer: "X" },
    { question: "화학 반응에서 질량은 항상 보존된다.", answer: "O" },
    { question: "산은 일반적으로 물에 녹아 수소 이온을 방출한다.", answer: "O" },
    { question: "지구의 자전축은 23.5도 기울어져 있다.", answer: "O" },
    { question: "산성 물질은 pH 값이 7보다 크다.", answer: "X" },
    { question: "물의 끓는점은 100도이다.", answer: "O" },
    { question: "대기의 대부분은 이산화탄소로 구성되어 있다.", answer: "X" },
    { question: "모든 포유류는 폐로 호흡한다.", answer: "O" },
    { question: "금은 주기율표에서 할로젠 원소에 속한다.", answer: "X" },
    { question: "원자 번호는 원자의 양성자 수를 의미한다.", answer: "O" },
    { question: "태양은 백색왜성이다.", answer: "X" },
    { question: "식물은 빛이 없어도 광합성을 할 수 있다.", answer: "X" },
    { question: "염화나트륨(NaCl)은 이온 결합에 의해 형성된 화합물이다.", answer: "O" },
    { question: "천왕성은 해왕성보다 태양에 더 가깝다.", answer: "O" },
    { question: "자석의 같은 극끼리는 서로 밀어낸다.", answer: "O" },
    { question: "산성 비는 일반적으로 pH가 5.6보다 낮다.", answer: "O" },
    { question: "모든 물질은 원자로 이루어져 있다.", answer: "O" },
    { question: "식물의 잎에서 기공을 통해 산소와 이산화탄소가 교환된다.", answer: "O" },
    { question: "대기 중의 이산화탄소 농도가 증가하면 온실 효과가 감소한다.", answer: "X" },
    { question: "소금물은 순수한 물보다 낮은 온도에서 어는점을 가진다.", answer: "O" },
    { question: "원자력 발전은 태양광 발전보다 더 안전하다.", answer: "X" },
    { question: "광물은 지구 내부에서 형성된 자연 발생 고체 물질이다.", answer: "O" },
    { question: "산화반응은 일반적으로 에너지를 방출한다.", answer: "O" },
    { question: "초신성 폭발은 새로운 별의 탄생을 의미한다.", answer: "X" },
    { question: "흑연은 탄소 원자들이 층으로 배열된 구조를 가지고 있다.", answer: "O" },
    { question: "물은 지구에서 가장 풍부한 화합물이다.", answer: "O" },
    { question: "모든 균류는 광합성을 한다.", answer: "X" },
    { question: "전자와 양성자는 서로 반대되는 전하를 갖는다.", answer: "O" },
    { question: "수성에는 대기가 거의 없다.", answer: "O" },
    { question: "빛은 진공에서 음속보다 느리게 이동한다.", answer: "X" },
    { question: "수소는 우주에서 가장 흔한 원소이다.", answer: "O" },
    { question: "구리는 철보다 더 강하다.", answer: "X" },
    { question: "소금(NaCl)은 전해질이다.", answer: "O" },
    { question: "지구의 맨틀은 고체 상태이다.", answer: "X" },
    { question: "모든 양서류는 물에서만 생활할 수 있다.", answer: "X" },
    { question: "공기의 온도가 높아지면 습도가 증가한다.", answer: "O" },
    { question: "빛의 속도는 물보다 진공에서 더 빠르다.", answer: "O" },
    { question: "지구의 중력은 해수면에서 가장 강하다.", answer: "O" },
    { question: "칼슘은 인체에 가장 풍부한 미네랄이다.", answer: "O" },
    { question: "바람은 고기압에서 저기압으로 불어간다.", answer: "O" },
    { question: "천왕성의 자전축은 거의 수직이다.", answer: "X" },
    { question: "모든 동물은 유전 물질로 DNA를 가지고 있다.", answer: "O" },
    { question: "바이러스는 스스로 에너지를 생성할 수 있다.", answer: "X" },
    { question: "태양은 우리 은하에서 가장 큰 별이다.", answer: "X" },
    { question: "세포막은 선택적으로 물질을 투과시킨다.", answer: "O" },
    { question: "물은 pH가 7인 중성 물질이다.", answer: "O" },
    { question: "철은 공기 중에서 쉽게 녹이 슨다.", answer: "O" },
    { question: "우주의 나이는 약 137억 년이다.", answer: "O" },
    { question: "인간의 유전자는 염색체에 저장된다.", answer: "O" },
    { question: "식물은 산소를 소비하고 이산화탄소를 방출한다.", answer: "O" },
    { question: "우주 공간에서는 음파가 전파될 수 없다.", answer: "O" },
    { question: "태양계에서 목성은 토성보다 더 큰 행성이다.", answer: "O" },
    { question: "식물은 이산화탄소를 흡수하고 산소를 방출한다.", answer: "O" },
    { question: "빛의 굴절률은 매질에 따라 달라진다.", answer: "O" },
    { question: "일산화탄소는 인체에 무해하다.", answer: "X" },
    { question: "물은 지구 표면의 약 70%를 덮고 있다.", answer: "O" },
    { question: "태양의 표면 온도는 약 5,500도이다.", answer: "O" },
    { question: "암석은 시간이 지나면서 풍화되어 토양을 형성한다.", answer: "O" },
    { question: "모든 기체는 열을 가하면 팽창한다.", answer: "O" },
    { question: "포도당은 탄소, 수소, 산소로 이루어진다.", answer: "O" },
    { question: "소리는 음파로 전달된다.", answer: "O" },
    { question: "모든 물질은 고체, 액체, 기체 중 한 상태로만 존재한다.", answer: "X" },
    { question: "수소는 물의 주요 구성 요소이다.", answer: "O" },
    { question: "지구 자전의 속도는 위도에 따라 다르다.", answer: "O" },
    { question: "호랑이는 야생에서 100년까지 살 수 있다.", answer: "X" },
    { question: "지구의 자전은 하루 동안의 시간을 결정한다.", answer: "O" },
    { question: "토성의 고리는 얼음과 암석으로 이루어져 있다.", answer: "O" },
    { question: "지구는 태양에 가장 가까운 행성이다.", answer: "X" },
    { question: "동물은 대사 과정에서 에너지를 생성한다.", answer: "O" },
    { question: "핵산은 유전 정보를 저장하는 역할을 한다.", answer: "O" },
    { question: "모든 금속은 전기를 잘 전도한다.", answer: "O" },
    { question: "대류는 물체가 직접 접촉하지 않고 열을 전달하는 과정이다.", answer: "X" },
    { question: "인간의 체온은 보통 약 37도이다.", answer: "O" },
    { question: "모든 식물은 씨앗을 통해 번식한다.", answer: "X" },
    { question: "물은 액체 상태에서 가장 밀도가 높다.", answer: "O" },
    { question: "달의 중력은 지구의 중력보다 강하다.", answer: "X" },
    { question: "태양은 하루 동안 동쪽에서 서쪽으로 이동한다.", answer: "O" }
];
